
const PARTICIPANTS={"grzegorz": {"name": "Grzegorz", "role": "Dowódca", "number": "OF-001", "icon": "🛡️", "mission": "Każdego dnia spraw, żeby każdy chłopak poczuł się choć raz naprawdę ważny.", "intro": "Dowódco, Twoja drużyna rusza za Tobą. Pilnuj humoru, bezpieczeństwa i magii całej wyprawy."}, "monika": {"name": "Ciocia Monika", "role": "Nawigator", "number": "OF-002", "icon": "🧭", "mission": "Zauważ dobre uczynki innych i przypomnij o nich podczas wieczornego raportu.", "intro": "Nawigatorze, Twoja uważność i dobre serce są jedną z największych sił Drużyny Feniksa."}, "marcel": {"name": "Marcel", "role": "Strateg", "number": "OF-003", "icon": "🏹", "mission": "Pomóż młodszemu bratu w jednej trudnej sytuacji i zachowaj to jako tajną misję.", "intro": "Strategu, Twoja misja to spryt, spokój i pomoc młodszym członkom drużyny."}, "filip": {"name": "Filip", "role": "Odkrywca", "number": "OF-004", "icon": "🔎", "mission": "Zauważ trzy rzeczy, których inni nie zauważyli, i opowiedz o nich wieczorem.", "intro": "Odkrywco, patrz uważnie. Najlepsze przygody często kryją się w szczegółach."}, "antek": {"name": "Antek", "role": "Tropiciel", "number": "OF-005", "icon": "🐾", "mission": "Każdego dnia znajdź jeden znak Feniksa i powiedz komuś coś miłego.", "intro": "Tropicielu, wielka odwaga nie zależy od wieku. Feniks liczy na Twoją energię."}};
const STAGES=[{"id": 1, "day": "Dzień 1", "title": "Start z Żurawicy", "icon": "🚗", "desc": "Pierwsza koperta, paszporty i początek wyprawy.", "reward": 3}, {"id": 2, "day": "Dzień 1", "title": "Baza Feniksa", "icon": "🏡", "desc": "Domek, rozpakowanie, pierwsze zadania i dart.", "reward": 3}, {"id": 3, "day": "Dzień 2", "title": "Mandoria", "icon": "🏰", "desc": "Atrakcje, odwaga, śmiech i pierwsze wielkie Pióra Feniksa.", "reward": 8}, {"id": 4, "day": "Dzień 2", "title": "Wieczorny raport", "icon": "🪶", "desc": "Najlepszy moment, najśmieszniejsza chwila i największa odwaga.", "reward": 4}, {"id": 5, "day": "Dzień 3", "title": "Hulajnogi i woda", "icon": "🛴", "desc": "Trasa, postoje, zdjęcia i misje terenowe.", "reward": 6}, {"id": 6, "day": "Dzień 3", "title": "Noc pod namiotem", "icon": "⛺", "desc": "Obóz, gry, klimat i nocna misja.", "reward": 5}, {"id": 7, "day": "Dzień 3", "title": "Skrzynia Feniksa", "icon": "📦", "desc": "Szyfr, wskazówki i otwarcie tajemnicy.", "reward": 5}, {"id": 8, "day": "Dzień 4", "title": "Escape Room", "icon": "🧩", "desc": "Ostatnia próba sprytu i współpracy.", "reward": 4}, {"id": 9, "day": "Dzień 4", "title": "Finał Operacji", "icon": "🏅", "desc": "Medale, certyfikaty, wspólne zdjęcie i zakończenie misji.", "reward": 2}];
const K='feniks_v4_';
function key(s){return K+s}
function getData(s){return JSON.parse(localStorage.getItem(key(s))||'{"coins":0,"stamps":0,"done":[],"notes":""}')}
function setData(s,d){localStorage.setItem(key(s),JSON.stringify(d))}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function renderProfile(slug){
 const p=PARTICIPANTS[slug], d=getData(slug);
 agentIcon.textContent=p.icon; agentName.textContent=p.name; agentRole.textContent=p.role+" • "+p.number; intro.textContent=p.intro; personalMission.textContent=p.mission;
 coins.textContent=d.coins; stamps.textContent=d.stamps; coinInput.value=d.coins; stampInput.value=d.stamps; notes.value=d.notes||"";
 bar.style.width=Math.min(100,(d.coins/40)*100)+"%"; stampView.textContent="■".repeat(d.stamps)+"□".repeat(12-d.stamps);
 rewardText.textContent=d.coins>=40?"TAJNA NAGRODA ODBLOKOWANA. Zgłoś się do Dowódcy Grzegorza.":"Brakuje jeszcze "+(40-d.coins)+" monet do tajnej nagrody.";
 stageList.innerHTML="";
 STAGES.forEach((m,i)=>{let div=document.createElement("div");div.className="card mission "+(d.done.includes(i)?"done":"");div.innerHTML=`<div class="ico">${m.icon}</div><div><b>${m.day} — ${m.title}</b><p>${m.desc}</p><p><b>Nagroda:</b> ${m.reward} monet</p><button onclick="toggleStage('${slug}',${i})">${d.done.includes(i)?"Cofnij wykonanie":"Oznacz jako wykonane"}</button></div>`;stageList.appendChild(div);});
}
function saveProfile(slug){let d=getData(slug);d.coins=clamp(parseInt(coinInput.value||0),0,40);d.stamps=clamp(parseInt(stampInput.value||0),0,12);d.notes=notes.value||"";setData(slug,d);renderProfile(slug)}
function addCoin(slug,a){let d=getData(slug);d.coins=clamp(d.coins+a,0,40);setData(slug,d);renderProfile(slug)}
function addStamp(slug,a){let d=getData(slug);d.stamps=clamp(d.stamps+a,0,12);setData(slug,d);renderProfile(slug)}
function toggleStage(slug,i){let d=getData(slug);if(d.done.includes(i)){d.done=d.done.filter(x=>x!==i);d.coins=clamp(d.coins-STAGES[i].reward,0,40)}else{d.done.push(i);d.coins=clamp(d.coins+STAGES[i].reward,0,40)}setData(slug,d);renderProfile(slug)}
function unlockMessage(){dailyMessage.textContent="Wiadomość Feniksa: dzisiaj szukaj nie tylko atrakcji, ale chwili, którą zapamiętasz na długo."}
function renderCommander(){commanderList.innerHTML="";Object.keys(PARTICIPANTS).forEach(slug=>{let p=PARTICIPANTS[slug],d=getData(slug),div=document.createElement("div");div.className="card";div.innerHTML=`<h2>${p.icon} ${p.name}</h2><p><b>${p.role}</b> • ${p.number}</p><p>🪙 Monety: <b>${d.coins}</b>/40 • Pieczęcie: <b>${d.stamps}</b>/12</p><button onclick="commanderAdd('${slug}',5,0)">+5 monet</button><button onclick="commanderAdd('${slug}',10,0)">+10 monet</button><button onclick="commanderAdd('${slug}',0,1)">+1 pieczęć</button><button onclick="commanderReset('${slug}')">Reset profilu</button>`;commanderList.appendChild(div);})}
function commanderAdd(slug,c,s){let d=getData(slug);d.coins=clamp(d.coins+c,0,40);d.stamps=clamp(d.stamps+s,0,12);setData(slug,d);renderCommander()}
function commanderReset(slug){if(confirm("Zresetować profil?")){setData(slug,{coins:0,stamps:0,done:[],notes:""});renderCommander()}}
